DROP FUNCTION IF EXISTS hello;
DELIMITER //
CREATE FUNCTION hello()
RETURNS varchar(100) DETERMINISTIC
BEGIN 
	RETURN 
	(SELECT CASE 
	WHEN CURTIME() BETWEEN '06:00' AND '11:59' THEN (SELECT 'Доброе утро') 
	WHEN CURTIME() BETWEEN '12:00' AND '17:59' THEN (SELECT 'Добрый день')
	WHEN CURTIME() BETWEEN '18:00' AND '23:59' THEN (SELECT 'Добрый вечер')
	WHEN CURTIME() BETWEEN '00:00' AND '05:59' THEN (SELECT 'Добрый ночи')								    
	   END);
END//

SELECT hello();

		
	